robotiq:
  sample_period: 1.0e-3
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500

  mimic_controller:
    type: robot_control/MimicController
    joint_names: # controlled joints
    - finger_joint
    - left_inner_finger_joint
    - left_inner_knuckle_joint
    - right_outer_knuckle_joint
    - right_inner_finger_joint
    - right_inner_knuckle_joint

    leading_joint: "finger_joint"  # leading joint

    # target position of a generic joint:  offset+multiplier*position of leading joint
    # target velocity of a generic joint:  multiplier*velocity of leading joint
    multiplier: [1.0, -1.0, 1.0, 1.0, -1.0, 1.0] #  (default 1.0)
    offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # (default null)

    Kp: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03 ] # position gain of controller
    Ki: [0.003, 0.003, 0.003, 0.003, 0.003, 0.003] # integral gain of the controller (default null)
    Kv: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1] # velocity gain of the controller (default null)
    max_effort: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3] # maximum effort of the joint
    setpoint_topic_name: "/robotiq/joint_target"
